### ISSUE TITLE
Alternative: using field option instead of field

### ISSUE THREAD

**Issue by xu-chris** [ian-cox/Kirby-Structure-Tabs#2]
As I wrote I've played a bit around with your awesome tabs. I've produced this blueprint snippet:

```
  events:
    label: Events
    type: eventlist
    fields:

      play:
        label: Aufführung
        type: structuretab
      play-item:
        label: Stück
        type: select
        options: query
        query:
          page: repertoire
          value: '{{uri}}'
          text: '{{title}}'
      play-informations:
        label: Weitere Spielplan-Informationen
        type: textarea
        size: small
      play-startdate:
        label: Von (Datum)
        type: date
        format: DD.MM.YYYY
        width: 1/2
        required: true
      play-starttime:
        label: Von (Zeit)
        type: time
        interval: 30
        default: 20:00
        width: 1/2
        required: true
      play-availability:
        label: Kartenbestand
        type: select
        default: InStock
        width: 1/2
        options:
          KartenVorhanden: Karten vorhanden
          FälltAus: Fällt aus
          NurAbendkasse: Nur Abendkasse
          NurOnlone: Nur Online
          Ausgebucht: Ausgebucht
          Frei: Freier Eintritt

      guest:
        label: Gastspiel
        type: structuretab
      guest-title:
        label: Stücktitel
        type: text
        help: Alternativ bei Gastspiel
      guest-informations:
        label: Weitere Spielplan-Informationen
        type: textarea
        size: small
      guest-startdate:
        label: Von (Datum)
        type: date
        format: DD.MM.YYYY
        width: 1/2
        required: true
      guest-starttime:
        label: Von (Zeit)
        type: time
        interval: 30
        default: 20:00
        width: 1/2
        required: true
      guest-enddate:
        label: Bis (Datum)
        type: date
        format: DD.MM.YYYY
        width: 1/2
        help: optional
      guest-endtime:
        label: Bis (Zeit)
        type: time
        interval: 30
        width: 1/2
        help: optional
      guest-dateattributes:
        label: Event-Merkmal
        type: tags
        separator: ", "
        lowercase: false
        width: 1/2
        data:
          - Premiere
          - B-Premiere
          - Deutsche Erstaufführung
          - Deutschsprachige Erstaufführung
          - öffentliche Probe
          - On Tour
          - Publikumsgespräch
          - Uraufführung
          - Voraufführung
          - Wiederaufnahme
          - Sondertermin für Gruppen
          - Sondertermin für KiTas
          - Sondertermin für Schulen
          - Zusatztermin
          - zum letzten Mal
          - zum letzten Mal in dieser Spielzeit
      guest-availability:
        label: Kartenbestand
        type: select
        default: InStock
        width: 1/2
        options:
          KartenVorhanden: Karten vorhanden
          FälltAus: Fällt aus
          NurAbendkasse: Nur Abendkasse
          NurOnlone: Nur Online
          Ausgebucht: Ausgebucht
          Frei: Freier Eintritt

      event:
        label: Sonstiges Event (z.B. TdoT)
        type: structuretab
      event-title:
        label: Event-Titel
        type: text
      event-informations:
        label: Weitere Spielplan-Informationen
        type: textarea
        size: small
      event-startdate:
        label: Von (Datum)
        type: date
        format: DD.MM.YYYY
        width: 1/2
        required: true
      event-starttime:
        label: Von (Zeit)
        type: time
        interval: 30
        default: 20:00
        width: 1/2
        required: true
      event-enddate:
        label: Bis (Datum)
        type: date
        format: DD.MM.YYYY
        width: 1/2
        help: optional
      event-endtime:
        label: Bis (Zeit)
        type: time
        interval: 30
        width: 1/2
        help: optional
      event-availability:
        label: Kartenbestand
        type: select
        default: InStock
        width: 1/2
        options:
          KartenVorhanden: Karten vorhanden
          FälltAus: Fällt aus
          NurAbendkasse: Nur Abendkasse
          NurOnlone: Nur Online
          Ausgebucht: Ausgebucht
          Frei: Freier Eintritt

      holidays:
        label: Ferien
        type: structuretab
      holidays-title:
        label: Pause-Titel
        type: text
        help: Alternativ bei Gastspiel
      holidays-informations:
        label: Weitere Spielplan-Informationen
        type: textarea
        size: small
      holidays-startdate:
        label: Von (Datum)
        type: date
        format: DD.MM.YYYY
        width: 1/2
        required: true
      holidays-starttime:
        label: Von (Zeit)
        type: time
        interval: 30
        default: 20:00
        width: 1/2
        required: true
      holidays-enddate:
        label: Bis (Datum)
        type: date
        format: DD.MM.YYYY
        width: 1/2
        help: optional
      holidays-endtime:
        label: Bis (Zeit)
        type: time
        interval: 30
        width: 1/2
        help: optional
```

I'm using the tabs to make my forms more easy and simple. As you can see I've produced multiple `startdate` and `title` fields and it feels wrong to use your tab plugin like this.

My naive version of this would be this:

```
events:
    label: Events
    type: eventlist
    fields:
      item:
        label: Stück
        type: select
        options: query
        width: 1/2
        tabs: Aufführung
        query:
          page: repertoire
          value: '{{uri}}'
          text: '{{title}}'
      title:
        label: Stücktitel
        type: text
        width: 1/2
        tabs: 
          - Gastspiel
          - Event
          - Ferien
        help: Alternativ bei Gastspiel
.
.
.
```

_(..and so on)_

As you see I would use a field option called `tabs` to specify in which tab I would like to see this item. And with this you could specify one or multiple tabs with dashes. If you want to use two fields in the same tab content you have to write the same tab name into this field option.

I don't know if this is possible but maybe this is something you would like to make. Of course the checkbox function of the tabs is still important. Maybe this could be combined with a invisible field which gets filled with the active field? Dunno..
