### ISSUE TITLE
Not working in Kirby 2.3

### ISSUE THREAD

**Issue by Thiousi** [ian-cox/Kirby-Structure-Tabs#3]
Fresh starterkit Kirby 2.3 install, simple blueprint: 

```
title: Project
pages: false
files:
  sortable: true
fields:
  title:
    label: Title
    type:  text
  modules:
    label: Structure test
    type: structure
    style: items
    modalsize: large
    fields:
      tab1:
        type: structuretab
        label: tab1
      text:
        label: Text
        type: text
        icon: header
      tab2:
        type: structuretab
        label: tab2
      text2:
        label: Text 2
        type: text
        icon: header
```

Result:
![image](https://cloud.githubusercontent.com/assets/4822666/16153279/f08dca9a-34a5-11e6-9b02-9702c6773d8e.png)

Analysis: seems like the javascript is completely ignored.
